services:
  - type: web
    name: sitemap-generator-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        # Replace this with your actual frontend URL once deployed
        value: https://your-frontend-url.onrender.com 